---
apiVersion: v1
kind: Template
objects:
  - apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: ${HTPASSWD_PROVIDER}
        mappingMethod: claim
        type: HTPasswd
        htpasswd:
          fileData:
            name: ${HTPASSWD_SECRET}
parameters:
- name: HTPASSWD_PROVIDER
  description: "Example Value - my_htpasswd_provider"
  required: true
- name: HTPASSWD_SECRET
  description: "Example Value - htpass-secret"
  required: true

